### ISSUE TITLE
PHP 8.0 | Backfill the new T_NULLSAFE_OBJECT_OPERATOR token

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#3040]
PHP 8 introduces a new object chaining operator `?->` which short-circuits moving to the next expression if the left-hand side evaluates to `null`.

Refs:
* https://wiki.php.net/rfc/nullsafe_operator
* https://github.com/php/php-src/commit/9bf119832dbf625174794834c71b1e793450d87f

### Impact for PHP_CodeSniffer

- [x] A backfill in the PHP tokenizer needs to be put in place to allow for this token. - PR #3046
    I have already prepared the necessary changes and will pull them once I've run some additional tests.

In addition to that, various sniffs will need to be adjusted to take the new token into account.

Initial inventory of affected sniffs:
- [x] Generic.NamingConventions.UpperCaseConstantName - PR #3079
- [x] Generic.PHP.ForbiddenFunctions - PR #3080
- [x] Generic.PHP.SAPIUsage - PR #3081
- [x] Generic.WhiteSpace.ScopeIndent - PR #3082
- [x] PEAR.WhiteSpace.ObjectOperatorIndent - PR #3083
- [x] PSR1.Files.SideEffects - PR #3084
- [x] PSR12.Classes.ClassInstantiation - PR #3085
- [x] Squiz.Formatting.OperatorBracket - PR #3086
- [x] Squiz.NamingConventions.ValidVariableName - PR #3087
- [x] Squiz.Operators.IncrementDecrementUsage - PR #3088
- [x] Squiz.PHP.DisallowSizeFunctionsInLoops - PR #3090
- [x] Squiz.PHP.LowercasePHPFunctions - PR #3091
- [x] Squiz.WhiteSpace.ObjectOperator - PR #3092
- [x] Zend.NamingConventions.ValidVariableName - PR #3093

I have commits ready for all sniffs with a checkmark and will pull those once the initial tokenizer changes have been merged.

Not claiming completeness, there may be more sniffs which need changes, but this should take care of the bulk of it.

**Comment by jrfnl** [comment]
All the commits I had ready & waiting for this have now been pulled.

**Comment by gsherwood** [comment]
That was an amazing set of PRs adding so much support. Thank you very much. I've still got a couple more to review but will get to those soon.

**Comment by gsherwood** [comment]
Going to close this now as all linked PRs have been merged. If anything else needs doing, it can be handled as new a PR.

Thanks again for the massive effort getting this in.

**Comment by jrfnl** [comment]
@gsherwood Actually, #3089 also still belongs with this series, even though it's more a "clean up" than "add support" type PR, but yes, all the "add support" type PRs have now been merged for this issue.
